import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  safeAreaCentered: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  infoText: {
    marginTop: 14,
    fontSize: 16,
    color: '#555',
    fontWeight: '500',
  },
   header: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#777',
  },
  iconBtnHeader: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#ebf3ff',
  },
  logoutBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#ffebee',
  },
  iconBtn: {
    padding: 6,
    marginLeft: 4,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#333',
  },
  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#edf2f7',
  },
  filterChipActive: {
    backgroundColor: '#2f6fed',
  },
  filterText: {
    fontSize: 12,
    color: '#4a5568',
    fontWeight: '600',
  },
  filterTextActive: {
    color: '#fff',
  },
  listContent: {
    padding: 16,
    paddingBottom: 100,
  },
  emptyContainer: {
    alignItems: 'center',
    marginTop: 60,
  },
  emptyText: {
    color: '#a0aec0',
    marginTop: 8,
    fontSize: 14,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#cbd5e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  checkboxDone: {
    backgroundColor: '#2f6fed',
    borderColor: '#2f6fed',
  },
  cardTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#2d3748',
  },
  cardTitleDone: {
    textDecorationLine: 'line-through',
    color: '#a0aec0',
  },
  thumbnail: {
    width: '100%',
    height: 160,
    borderRadius: 10,
    marginTop: 12,
  },
  zoomBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    backgroundColor: 'rgba(0,0,0,0.6)',
    padding: 4,
    borderRadius: 6,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 4,
  },
  coordsText: {
    color: '#2f6fed',
    fontSize: 12,
    fontWeight: '500',
    flex: 1,
  },
  dateText: {
    color: '#a0aec0',
    fontSize: 11,
    marginTop: 8,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#2f6fed',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#2f6fed',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '88%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 12,
    minHeight: 70,
    textAlignVertical: 'top',
    fontSize: 15,
    marginBottom: 10,
  },
  modalInputSingle: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    marginBottom: 12,
    backgroundColor: '#fff',
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4a5568',
    marginBottom: 4,
  },
  gpsAlertBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffebee',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
    gap: 8,
  },
  gpsAlertBoxOk: {
    backgroundColor: '#e8f5e9',
  },
  gpsAlertText: {
    fontSize: 12,
    color: '#c62828',
    flex: 1,
  },
  gpsAlertTextOk: {
    color: '#2e7d32',
  },
  previewContainer: {
    position: 'relative',
    marginBottom: 12,
  },
  previewImage: {
    width: '100%',
    height: 140,
    borderRadius: 10,
  },
  removePhotoBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: '#fff',
    borderRadius: 12,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
  },
  mediaButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    paddingVertical: 10,
    backgroundColor: '#f8f9fa',
  },
  mediaButtonActive: {
    backgroundColor: '#2f6fed',
    borderColor: '#2f6fed',
  },
  mediaButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#2f6fed',
  },
  mediaButtonTextActive: {
    color: '#fff',
  },
  primaryBtn: {
    backgroundColor: '#2f6fed',
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
  },
  primaryBtnText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  zoomModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeZoomBtn: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 10,
    padding: 8,
  },
  zoomImage: {
    width: width,
    height: '80%',
  },
  profileAvatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
  },
  avatarPlaceholder: {
    backgroundColor: '#edf2f7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarButtonsRow: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 0,
    right: -10,
    gap: 6,
  },
  avatarMiniBtn: {
    backgroundColor: '#2f6fed',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  profileScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
    alignItems: 'center',
  },

// Barra de Pastas
  folderBarContainer: {
    backgroundColor: '#fff',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#edf2f7',
  },
  folderTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#edf2f7',
    gap: 6,
  },
  folderTabActive: {
    backgroundColor: '#2f6fed',
  },
  folderTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4a5568',
  },
  folderTabTextActive: {
    color: '#fff',
  },
  folderTabAdd: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#2f6fed',
    borderStyle: 'dashed',
    gap: 4,
  },
  folderTabAddText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#2f6fed',
  },
  folderBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#edf2f7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginTop: 4,
    gap: 4,
  },
  folderBadgeText: {
    fontSize: 11,
    color: '#2f6fed',
    fontWeight: '600',
  },
  folderSelectChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2f6fed',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    backgroundColor: '#fff',
  },
  folderSelectChipActive: {
    backgroundColor: '#2f6fed',
  },
  folderSelectChipText: {
    fontSize: 12,
    color: '#2f6fed',
    fontWeight: '600',
  },
  folderSelectChipTextActive: {
    color: '#fff',
  },
  folderModalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },

  // Dropdown do Header
  headerFolderDropdown: {
    flex: 1,
    marginRight: 10,
  },
  folderDropdownBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#f8f9fa',
    marginBottom: 14,
  },
  folderDropdownBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2d3748',
  },
  sheetContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '80%',
    minHeight: 350,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  btnOpenCreateFolder: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#edf2f7',
    borderRadius: 10,
    marginBottom: 12,
  },
  btnOpenCreateFolderText: {
    color: '#2f6fed',
    fontSize: 14,
    fontWeight: '700',
  },
  createFolderRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
    alignItems: 'center',
  },
  createFolderInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#2f6fed',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  createFolderConfirmBtn: {
    backgroundColor: '#2f6fed',
    padding: 10,
    borderRadius: 8,
  },
  createFolderCancelBtn: {
    backgroundColor: '#eee',
    padding: 10,
    borderRadius: 8,
  },
  folderSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 10,
    gap: 6,
  },
  folderSearchInput: {
    flex: 1,
    fontSize: 13,
  },
  folderListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  folderListItemActive: {
    backgroundColor: '#ebf3ff',
  },
  folderListItemText: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  folderListItemTextActive: {
    color: '#2f6fed',
    fontWeight: '700',
  },

});

export default styles;